#!/bin/bash

VERSION=1.33
PACKAGE=fastani
TOOL=fastANI
DIRECTORY=$(dirname $0)

PERSISTENT_FILE_STORAGE=/ocean
if [ ! -d $PERSISTENT_FILE_STORAGE ]; then
	singularity exec $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
else
	singularity exec -B $PERSISTENT_FILE_STORAGE $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
fi
